# Generated by Django 3.2.8 on 2021-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211020_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
    ]
