# Generated by Django 3.2.8 on 2021-10-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
