# Generated by Django 3.2.8 on 2021-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211019_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
