# Generated by Django 3.2.8 on 2021-10-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsession_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
    ]
