# Generated by Django 3.2.8 on 2021-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chattemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_agent_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chattemplate',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
