# Generated by Django 3.2.8 on 2021-10-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20211021_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-id']},
        ),
    ]
