# Generated by Django 3.2.8 on 2021-10-27 16:01

import chat.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chatsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Allowed extensions: png & jpg', null=True, upload_to=chat.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='chattemplate',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
